version: '2'
services:
  cp3_ta:
    image: cmumars/p2-cp3
    container_name: cp3_ta
    environment:
      - "ROS_MASTER=http://cp3_ta:11311"
      - "ROS_HOSTNAME=cp3_ta"
      - "TA_PORT=${TA_PORT}"
      - "HARD_FAIL_ON_ECS=false"
    volumes:
      - ./logs:/home/mars/logs
      - ./roslogs:/home/mars/logs
    ports:
      - ${TA_PORT}:5000
    expose:
      - 5000
    command: bash -c "sleep 5 && . ~/catkin_ws/entrypoint.sh && cd /usr/src/app && ./start_exp.sh http://$DOCKERHOST:8080"
